<style>
</style>
<!--<img src="../../../assets/images/00setup.png" alt="Setup">-->
<h4 class="subtitle"><b>[01]</b> Citizen C.I.A.</h4>
<ul>
  <li>
    <b>Confidentiality:</b> only authorized persons have seen the data.
  </li>
  <li>
    <b>Integrity:</b> The data hasn't been modified by unauthorized
    persons. It refers to data integrity at all points in the network,
    from VPN transfer to storage and everything in between (from the data
    is created until it's destroyed).
  </li>
  <li>
    <b>Availability:</b> The data is available to authorized persons when
    and where they need it.
  </li>
</ul>
<h4 class="subtitle"><b>[02]</b> Intro to SIEM</h4>
<ul>
  <li>
    <b>SIEM</b>: <b>Security Information and Event Management</b>: SIEM
    software products provide <i>real-time</i> analysis of security alerts
    generated by network hardware and applications. There are 3 tasks
    a SIEM solution simply must carry on:
    <ul>
      <li>
        Data <b>aggregation</b>
      </li>
      <li>
        Data <b>correlation</b>
      </li>
      <li>
        Data <b>retention</b>
      </li>
    </ul>
  </li>
  <li>
    A SIEM solution must be able to collect and aggregate data from
    multiple networks and multiple devices in the same network: firewalls,
    IPSs, antivirus software, Windows logs, routers, switches...
  </li>
  <li>
    When you start a SIEM solution, you are likely to discover you are
    collecting redundant data from logs at different points in your network,
    so ou can <b>reduce</b> the amount/number of logs.
  </li>
  <li>
    Note about logging: it is VITAL to have <b>consistent timestamps</b>
    on your logs.
  </li>
  <li>
    It's the job of the correlation process to notice malicious behaviour
    patterns or events across our network by analazing aggregated data. They
    create a profile (baseline) of how things look when everything is running
    cleanly and smoothly, to have something to compare to.
  </li>
  <li>
    Correlation is dependent on both data aggregation and <i>retention</i> (which
    is ensuring that data is archived for a given period of time).
  </li>
</ul>
<h4 class="subtitle"><b>[03]</b> SIEM: What is it good for?</h4>
<ul>
  <li>
    Some companys get a SIEM system strictly to meet external requirements.
    If this is the case, make sure you SIEM will do so. Ask the vendor
    directly if the SIEM system meets said requirements, and get that in
    writing. Same goes for internally developed requirements.
  </li>
  <li>
    The key to success here: <i>knowing what you're trying to protect</i>.
    This isn't just true of choosing a SIEM solution. It's true of purchasing
    anything from a SIEM solution to antivirus software.
  </li>
</ul>
<h4 class="subtitle"><b>[04]</b> Recon attacks and phishing</h4>
<ul>
  <li>
    The entire point of <b>reconnaissance attack</b> is to gather information
    for future attacks and go unnoticed.
  </li>
  <li>
    The recon attack searches for weaknesses, or vulnerabilities, in our
    network defenses. When they are found, they are not exploited by
    a recon attack.
  </li>
  <li>
    <b>Social engineering attacks</b> focus their energies on the most
    unpredictable part of our network - the <i>human being</i>. Instead
    of trying to poke holes in our firewall or some other assault on
    hardware, these attacks focus on using human emotions to carry out
    an assault, particularly joy and fear.
  </li>
  <li>
    <b>Phishing</b> is often carried out by sending a link in an email
    that purports to be from a bank, the nation's tax collector, eBay,
    PayPal... They're all about making the reader happy or fearful. The
    content is non-especific: "Dear Sir or Madam". An attacker sends
    thousands or millions of copies at the same time.
  </li>
</ul>
<h4 class="subtitle"><b>[05]</b> Spear Phishing, QPQ and Pretexting</h4>
<ul>
  <li>
    A <b>spear phishing</b> attacker sends an email directly to the
    victim-to-be that oozes with familiarity. The attacker uses information
    that most people keep on their personal Facebook page (or any other
    social media). An example: the attacker pretends to be a network
    admin for the vitctim's compane, and asks him to log in to a "new login
    page" they are testing out.
  </li>
  <li>
    <b>Quid pro quo</b> ("this for that"):
    the attacker pretends to be someone he's not and promises to do
    something for you in exchange for you doing something for him.
    Ex: "do this survey and I give you some free antivirus updates"
    (packed with malware).
  </li>
  <li>
    <b>Pretexting</b>: the attacker asks for information under a false
    pretext: "I'm Jim Harrison with Santander Baking, and we believe
    someone is trying to hack your bank account! We need to verify your
    withdrawals. Can you give me your account number?".
  </li>
</ul>
<h4 class="subtitle"><b>[06]</b> Privilege Escalation and Telnet</h4>
<ul>
  <li>
    VLAN 1 is the only switch virtual interface that is on the switch
    by default. It is administratively down (needs <b>no shut</b>).
  </li>
</ul>
<pre class="terminal">SW2# <b>sh int vlan 1</b>
Vlan1 is up, line protocol is down
  Hardware is EtherSVI, address is c202.0a4f.0000 (bia c202.0a4f.0000)
  MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100 usec,
!... many more lines

SW2# <b>sh int vlan 12</b>
             ^
% Invalid input detected at &apos;^&apos; marker.
</pre>
<h4 class="subtitle"><b>[07]</b> </h4>
<ul>
  <li>

  </li>
</ul>
<h4 class="subtitle"><b>[08]</b> </h4>
<ul>
  <li>

  </li>
</ul>
<h4 class="subtitle"><b>[09]</b> </h4>
<ul>
  <li>

  </li>
</ul>
<h4 class="subtitle"><b>[10]</b> </h4>
<ul>
  <li>

  </li>
</ul>
<h4 class="subtitle"><b>[11]</b> </h4>
<ul>
  <li>

  </li>
</ul>
<h4 class="subtitle"><b>[12]</b> </h4>
<ul>
  <li>

  </li>
</ul>
<h4 class="subtitle"><b>[06]</b> </h4>
<ul>
  <li>

  </li>
</ul>
